# Generated by Django 4.1.7 on 2023-08-03 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_productos_creado_en'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
    ]
